### PR TITLE
Add 6.4 branch

### PR DESCRIPTION
**Pull request by tinywrkb**
Draft, ~~as I was forced to enable FFmpeg static linking. This should be resolved.~~  
Another possible change is stopping to fetch the latest commit for QtWebEngine's Chromium fork. Seeing the number of PRs that were accumulated, and the very little attention this base app get, I think it's better to limit update PRs to minimal.

Works fine locally, just testing here the CI, and getting feedback.
As usual, should be merged into a new `branch/6.4 branch` when ready.

### CODE REVIEW

**Comment by aleixpol** [comment]
Change looks good, we could get it in.

Using the tarballs instead of git versions would resolve the chromium version problem. Also using the integrated submodules.

**Comment by JakobDev** [comment]
@tinywrkb Any News on this?

**Comment by hfiguiere** [comment]
Is this really ready to merge? I can push a branch.

**Comment by recioalex** [comment]
I would love to see this pushed. ¿Is there anything i can help with?

**Comment by hfiguiere** [comment]
Pushed as `branch/6.4`

Please report any issues.

**Pull request closed without merging**
