### PR TITLE
[branch/6.3] Update runtime and Qt modules to 6.3

### PR DESCRIPTION
**Pull request by tinywrkb**
**Do not merge to 6.2!** Needs a new 6.3 branch.

## Changes
* Update runtime and Qt modules to 6.3
  * Python 2 is finally gone
  * Added explicit config options for documenting the runtime libs used by Chromium instead of
    statically link against the ones that are distributed in Chromium's source.
* QtWebEngine: Update sandboxing patches for 94
* qtwebengine-dictionaries: Fix typos and other errors in comments
* qt6-webview: Add shared lib symlinks in lib/
* README.md: Link to the wiki
* qt6-webview: Set source as important for selective f-e-d-c updates
* flathub.json: Activate selective f-e-d-c updates  
**This will do nothing** as we're using our own Github workflow, but let's set this for the possibility that flathubbot
will support checking multiple branches.
- qtwebengine-chromium: Use JSON checker, don't break on outdated commit

### CODE REVIEW

**Comment by tinywrkb** [comment]
I will trigger a test build to confirm that this actually works correctly after the buildbot-config PR is merged and that the runtime is published.

**Comment by tinywrkb** [comment]
bot, build io.qt.qtwebengine.BaseApp

**Comment by tinywrkb** [comment]
@aleixpol If this builds, then feel free to merge this into a new 6.3 branch.

**Comment by tinywrkb** [comment]
Looking great!  
I built an updated PyQt base application with this, tested qutebrowser, Calibre, and haven't noticed any problem.  
Ready for merging.

**Comment by tinywrkb** [comment]
Switched to draft for testing system FreeType2 and QtPDF modules.

**Comment by tinywrkb** [comment]
Switched to draft to add properties for the new selective update support in f-e-d-c.

**Comment by tinywrkb** [comment]
Ready for merging.

**Comment by tinywrkb** [comment]
Switching to draft to update qtwebengine-chromium checker, so it could work with f-e-d-c selective updates.

**Comment by hfiguiere** [comment]
Branch has been created.

Thanks!

**Pull request closed without merging**
