### PR TITLE
WIP: Do Not Merge (wrong branch): Update to 22.08 Runtime

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
bot, build

**Comment by tinywrkb** [comment]
No 22.08 branch for Node.js v14. You should be able to use v18, as I believe that this is what Arch Linux use without any extra related patches.

**Comment by tinywrkb** [comment]
Looks like the Python3 patch need to be updated for Python 3.10, as that Jinja2 Python module is likely from Chromium tree.  
The author of this patch is Antonio Rojas, his updated patch is [here](https://github.com/archlinux/svntogit-packages/tree/packages/qt5-webengine/trunk), and we should probably pick up the other Python3 patch that was added.

BTW, you should run f-e-d-c to update qtwebengine-chromium to latest commit, as there seem to be a security backport there in the 87-based branch, and also there's a new QtWebView release as part of Qt 5.15.6.

**Comment by hfiguiere** [comment]
There is more that just python 3.10 shenanigans. There is also some ffmpeg 5 issues (system ffmpeg) and the patch for AUR doesn't work either.
See https://github.com/nwjs-ffmpeg-prebuilt/nwjs-ffmpeg-prebuilt/issues/117#issuecomment-1126744011

**Comment by hfiguiere** [comment]
Pushed my current WIP (didn't see this PR at first) as https://github.com/flathub/io.qt.qtwebengine.BaseApp/tree/5.15-22.08-submission. It doesn't build either, but at least it's easier to collaborate on it.

**Comment by hfiguiere** [comment]
see #117

**Comment by hfiguiere** [comment]
If anyone can help testing the build for #117. The main change is that it no longer uses system ffmpeg.

**Pull request closed without merging**
