### PR TITLE
[branch/5.15-21.08] Switch to PipeWire 0.3

### PR DESCRIPTION
**Pull request by tinywrkb**
Screensharing via PipeWire is currently broken with Sway in updated systems that have a recent PipeWire 0.3 release. For example, the issue is occurring with qutebrowser as described in qutebrowser/qutebrowser/issues/6752.

Try avoiding the issue by switching to PipeWire 0.3.

**Changes:**

* Add PipeWire 0.3 patch backported by Antonio Rojas, Arch Linux maintainer of the qt5-webengine package.
* Drop the pipewire 0.2 module.
* Minor cosmetics change in the polish module.

~~Mark as draft as it was tested yet.~~

### CODE REVIEW

**Comment by tinywrkb** [comment]
Looks good! Screen sharing is now working with qutebrowser.  
Host system with Sway 1.7, PipeWire 0.3.45, xdg-desktop-portal 1.12.1, xdg-desktop-portal-wlr 0.5.0.

**Comment by grulja** [comment]
Looks good to me.

**Comment by aleixpol** [comment]
Okay, let's go with this then, thanks!

**Comment by tinywrkb** [comment]
Thanks for merging!

**Pull request merged**
