### PR TITLE
Qt webengine 6.6.0

### PR DESCRIPTION
**Pull request by bbhtt**
6.6 is not out yet, I'll cancel the build and start again when it is out.

### CODE REVIEW

**Comment by bbhtt** [comment]
I'll trigger a build later. Github is having API issues at the moment.

Since you both reviewed, 6.4 and 6.5 branch PRs respectively, it'd be great if you can review this one too. Thanks

If it builds I can create the branch and push, or maybe aleixpol is willing to do it? I see that you're the maintainer.

**Comment by tsdgeos** [comment]
I do not have merging rights here.

**Comment by hfiguiere** [comment]
Do you want me to push to / create the branch?

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
The runner got oom killed

**Comment by bbhtt** [comment]
Ah no I broke one patch, will fix

```
../../../../../src/3rdparty/chromium/content/zygote/zygote_main_linux.cc: In function ‘void content::EnterLayerOneSandbox(sandbox::policy::SandboxLinux*, bool, bool, base::OnceClosure)’:
../../../../../src/3rdparty/chromium/content/zygote/zygote_main_linux.cc:164:31: error: ‘using_layer2_sandbox’ was not declared in this scope; did you mean ‘using_layer1_sandbox’?
  164 |   if (using_layer1_sandbox || using_layer2_sandbox)
```

**Comment by bbhtt** [comment]
Not exactly sure where the if condition is coming from, upstream chromium never had it https://github.com/chromium/chromium/blob/b0c78a4bcbe1a7d7e78938e8b20f31892c62a8f9/content/zygote/zygote_main_linux.cc#L145 as far back as 2015 and this wasn't part of any patch sets here.

Anyway removed it.

**Comment by bbhtt** [comment]
> Do you want me to push to / create the branch?

Yea sure. I can do it too if you're busy.

I wanted a review first.

**Comment by bbhtt** [comment]
Branch created https://github.com/flathub/io.qt.qtwebengine.BaseApp/commits/branch/6.6/ and pushed

Build https://buildbot.flathub.org/#/builders/6/builds/77443

**Pull request closed without merging**
