### PR TITLE
Update qtwebengine to v5.15.16-lts (branch/5.15-23.08)

### PR DESCRIPTION
**Pull request by bbhtt**
See https://github.com/flathub/io.qt.qtwebengine.BaseApp/pull/324

### CODE REVIEW

**Comment by AsciiWolf** [comment]
It looks like that this issue is still happening on the 5.15-23.08 branch.

**Comment by bbhtt** [comment]
> It looks like that this issue is still happening on the 5.15-23.08 branch.

what issue?

**Comment by AsciiWolf** [comment]
Sorry, I meant the `flathub-json-skip-appstream-check` one that looks to be caused by this base app (and should have been fixed by one of this PR's commits). See this build log: https://buildbot.flathub.org/#/builders/6/builds/83603

**Comment by bbhtt** [comment]
> Sorry, I meant the `flathub-json-skip-appstream-check` one that looks to be caused by this base app (and should have been fixed by one of this PR's commits). See this build log: https://buildbot.flathub.org/#/builders/6/builds/83603

That fixes it for this baseapp only, but now flathub.json from the baseapp is coming into the app and skip-appstream-check isn't allowed for regular apps. You should something like this to clean it up in apps:

```json
    {
        "name": "cleanup-flathub-json",
        "buildsystem": "simple",
        "build-commands": [
            "rm -rvf ${FLATPAK_DEST}/flathub.json"
        ]
    }
```

```yaml
  - name: cleanup-flathub-json
    buildsystem: simple
    build-commands:
      - rm -rvf ${FLATPAK_DEST}/flathub.json
```

This is temporary. See the discussion here https://github.com/flathub/flathub/issues/4693#issuecomment-1825983345

**Comment by AsciiWolf** [comment]
Ah, thanks for the info! :-)

**Pull request merged**
