### PR TITLE
Update runtime to 6.2 and QtWebEngine to 6.2.2

### LINKED ISSUE #25: Add support for Qt6
Would be nice you could add supp0ort for Qt 6.

### PR DESCRIPTION
**Pull request by tinywrkb**
**This shouldn't be merged, it needs to be pulled into a new `branch/6.2` branch.**  

Update runtime to 6.2 and QtWebEngine to 6.2.2

## Highlights:
  - Directory structure now follows `qt.toolchain.cmake`.
      - The environment variable `QMAKEPATH` should now be set to `/app`, if needed, when building a Flatpak app.
        For example, the variable should be set when building PyQt6-WebEngine
      - Regression: the CMake variable `_qt_additional_packages_prefix_paths` should be set to
        `/app/lib/<ARCH>-linux-gnu/cmake`, e.g. `/app/lib/x86_64-linux-gnu/cmake`
        This would not be needed once [this MR](https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/67) is         merged, and the runtime is updated.
  - No need to set `QMAKE_INCDIR`
  - New shared libs: `krb5`, `libevent`, `minizip`, `pciutils`, `re2`, `snappy`
  - QtWebView was added

## Changes:
  - Switch to KDE 6.2 runtime
  - Update QtWebEngine to 6.2.2
  - Update QtWebEngine patches
  - Drop PipeWire 0.2 module, as we now have Chromium 90 with PipeWire 0.3 support
  - Use FLATPAK_DEST as much as possible
  - pciutils: drop PREFIX install arg
  - Simpler workaround for the Qt patch version dependency
  - Add QtWebView
  - Add krb5 and enable Kerberos in QtWebEngine
  - Use FLATPAK_ARCH instead of executing `gcc --print-multiarch`
  - Move modules into separate manifests that can be tested without having to build the base app
  - Avoid Chromium in-tree libs by adding them as modules: `libevent`, `minizip`, `re2`, `snappy`
  - Add chromium-add-app-libdir.patch as a workaround for gn not finding libevent when linking Chromium
  - Keep pciutils as a shared lib in the base app
  - INSTALL_ROOT install variable/config is not supported anymore, and DESTDIR follows `qt.toolchain.cmake`
    from the runtime.
    Qt dirs in the `/app` prefix are now in the same directory structure as in the runtime prefix `/usr`
    This means that `QMAKEPATH` is now `/app`
  - Disable locale extensions creation now that we have `/app/share/locale`
  - No need to set `QMAKE_INCDIR` anymore (e.g `QMAKE_INCDIR+=/app/include/QtWebEngineCore`), as include dirs
    path in modules' project include files (pri) are now correct

Closes #25

## TODO

* [x] Solve the `find_package` path issue. Won't fix here, see [runtime MR](https://invent.kde.org/packaging/flatpak-kde-runtime/-/merge_requests/67)
* [x] Build apps/libs against QtWebEngine to test the base app packaging
  * [x] [qutebrowser](https://github.com/tinywrkb/org.qutebrowser.qutebrowser/tree/pyqt6) (PyQt6-WebEngine)
  * [x] [Jami](https://github.com/flathub/net.jami.Jami)

### CODE REVIEW

**Comment by tinywrkb** [comment]
`x86_64` build failed after `qt6-qtwebengine` module configure step with the error

> bwrap: Can't get type of source /srv/buildbot/.cache/.flatpak/1478747088: No such file or directory

This doesn't happen when building locally, so it might be a temporary CI issue. I'll force a rebuild later, as the `aarch64` worker is still building.

**Comment by tinywrkb** [comment]
I forgot to update the `make-install-args` array, so the installation step failed, but at least it looks like Chromium's build step can complete correctly. I'll try rebuilding again after my local build run will end.

**Comment by tinywrkb** [comment]
Build successful, but it's not ready for review yet. I will remove the draft when it is ready.

**Comment by tinywrkb** [comment]
Patch versions of QtWebEngine and QtWebView are different from Qt6 patch version from the runtime, so changes to CMake configs of QtWebEngine and QtWebView are needed.  
I hastily updated these configs, so my changes might not be correct.  
That being said, the currently running build 72437, which I expect to be built successfully, might be worthy of testing.

**Comment by tinywrkb** [comment]
Previous test builds introduce locale extensions, so they were not usable, as the locale symlinks were pointing nowhere during app build.  
Test build 72528 disables locale extensions generation.

I'm now running qutebrowser with QtWebEngine 6, see my [pyqt6 branch](https://github.com/tinywrkb/org.qutebrowser.qutebrowser/tree/pyqt6). I have PyQt6 and PyQt6-WebEngine packaging there.  
Note that you need the currently running build 72528, or remove the locale symlinks from a previous build.

**Comment by FuchtelJockel** [comment]
I tested build 72528 with https://github.com/flathub/net.jami.Jami and can confirm that it works!
I only had to add:
```
-DQt6WebEngineCore_DIR=/app/lib/x86_64-linux-gnu/cmake/Qt6WebEngineCore
-DQt6WebEngineQuick_DIR=/app/lib/x86_64-linux-gnu/cmake/Qt6WebEngineQuick
-DQt6WebEngineWidgets_DIR=/app/lib/x86_64-linux-gnu/cmake/Qt6WebEngineWidgets
```
but this could be build system issue.

**Comment by tinywrkb** [comment]
@FuchtelJockel thank you for testing.  
I also hit the same issue when packaging QtWebView. I'm not sure what's the best way to fix this, but you can also set `_qt_additional_packages_prefix_paths`.  
For `jami-libclient`, taking into account the existing `config-opts` array, it should look like this:

```
build-options:
  arch:
    x86_64:
      config-opts:
        - -D_qt_additional_packages_prefix_paths=/app/lib/x86_64-linux-gnu/cmake
        - -DCMAKE_BUILD_TYPE=None
    aarch64:
      config-opts:
        - -D_qt_additional_packages_prefix_paths=/app/lib/aarch64-linux-gnu/cmake
        - -DCMAKE_BUILD_TYPE=None
```

There's also `QT_ADDITIONAL_PACKAGES_PREFIX_PATH` which can be set through a CMake var and environment var (to the value `/app`), but `Qt6Config.cmake` append `/lib/cmake` to it.

Maybe the correct place to fix this is in the runtime's `Qt6Config.cmake`.

**Comment by JakobDev** [comment]
I have a PyQt6 Program which uses QtWebEngine. I had this manifest included:

PyQt6.yml
```yaml
name: pyqt6
modules:

  - name: sip
    buildsystem: simple
    build-commands:
      - pip3 install --no-deps --no-use-pep517 --prefix=$FLATPAK_DEST .
    sources:
      - type: archive
        url: https://pypi.python.org/packages/source/s/sip/sip-6.4.0.tar.gz
        sha256: 42ec368520b8da4a0987218510b1b520b4981e4405086c1be384733affc2bcb0
    modules:

      - name: python-toml
        buildsystem: simple
        build-commands:
          - pip3 install --no-deps --no-use-pep517 --prefix=$FLATPAK_DEST .
        sources:
          - type: archive
            url: https://files.pythonhosted.org/packages/source/t/toml/toml-0.10.0.tar.gz
            sha256: 229f81c57791a41d65e399fc06bf0848bab550a9dfd5ed66df18ce5f05e73d5c

      - name: python-packaging
        buildsystem: simple
        build-commands:
          - pip3 install --no-deps --no-use-pep517 --prefix=$FLATPAK_DEST .
        sources:
          - type: archive
            url: https://files.pythonhosted.org/packages/source/p/packaging/packaging-20.1.tar.gz
            sha256: e665345f9eef0c621aa0bf2f8d78cf6d21904eef16a93f020240b704a57f1334
        cleanup:
          - "*"

  - name: sip-pyqt6
    buildsystem: simple
    build-commands:
      - pip3 install --no-deps --no-use-pep517 --prefix=$FLATPAK_DEST .
    sources:
      - type: archive
        url: https://pypi.python.org/packages/source/P/PyQt6-sip/PyQt6_sip-13.1.0.tar.gz
        sha256: 7c31073fe8e6cb8a42e85d60d3a096700a9047c772b354d6227dfe965566ec8a

  - name: python-pyparsing
    buildsystem: simple
    build-commands:
      - pip3 install --no-deps --no-use-pep517 --prefix=$FLATPAK_DEST .
    sources:
      - type: archive
        url: https://files.pythonhosted.org/packages/source/p/pyparsing/pyparsing-2.4.6.tar.gz
        sha256: 4c830582a84fb022400b85429791bc551f1f4871c33f23e44f353119e92f969f
    cleanup:
      - "*"

  - name: PyQt-builder
    buildsystem: simple
    build-commands:
      - pip3 install --no-deps --no-use-pep517 --prefix=$FLATPAK_DEST .
    sources:
      - type: archive
        url: https://files.pythonhosted.org/packages/8b/5f/1bd49787262ddce37b826ef49dcccf5a9970facf0ed363dee5ee233e681d/PyQt-builder-1.12.2.tar.gz
        sha256: f62bb688d70e0afd88c413a8d994bda824e6cebd12b612902d1945c5a67edcd7
    cleanup:
      - "*"

buildsystem: simple
build-commands:
  - sip-install
    --confirm-license
    --no-designer-plugin
    --no-qml-plugin
    --no-tools
    --concatenate=1
    --debug
    --no-docstrings
    --verbose
    --qt-shared
    --target-dir=/app/lib/python_pyver/site-packages/
    --enable=QtCore
    --enable=QtWidgets
    --enable=QtGui
    --enable=QtNetwork
    --enable=QtWebChannel
    --enable=QtQml
    --enable=QtPrintSupport
sources:
  - type: archive
    url: https://pypi.python.org/packages/source/P/PyQt6/PyQt6-6.2.1.tar.gz
    sha256: d603a5c8effccc9174b3f43834256401a61ea40f2338306ca22fb6a1e870b89c
```

PyQt6-Webengine.yml
```yaml
name: pyqt6-webengine
buildsystem: simple
build-commands:
  - sip-install
    --debug
    --verbose
    --concatenate=1
    --no-docstrings
    --qmake=/usr/bin/qmake6
    --api-dir=/app/lib/python_pyver/site-packages/
    --target-dir=/app/lib/python_pyver/site-packages/
sources:
  - type: archive
    url: https://pypi.python.org/packages/source/P/PyQt6-WebEngine/PyQt6_WebEngine-6.2.1.tar.gz
    sha256: 6f6d7cb612f20d1f1f8ea1bbe7ebb8bbaa3f7fcd56f0e9c41582851998be20c3
```

PyQt6 works without any problems and is already used by one of my programs but PyQt6-Qwbengine fails with
```
Project ERROR: Unknown module(s) in QT: webenginecore
```
I had already tried to copy the PyQt6 folder (not the rest) from qutebrowser  but it doesn't work. I use Kde Platform and KDE SDK 6.2 and Version 6.2 of the latest build here as base App. I had absolutely no experience in the build system and I#m a absolutely C/C++ noob, so it would be nice if one of you could say me what arguments are needed here to build the WebEngine Bindings.

**Comment by tinywrkb** [comment]
@JakobDev set `QMAKEPATH=/app` like I'm doing [here](https://github.com/tinywrkb/org.qutebrowser.qutebrowser/blob/pyqt6/pyqt6/pyqt6-webengine.json).

**Comment by JakobDev** [comment]
> @JakobDev set `QMAKEPATH=/app` like I'm doing [here](https://github.com/tinywrkb/org.qutebrowser.qutebrowser/blob/pyqt6/pyqt6/pyqt6-webengine.json).

Unfortunately this doesn't help.

PyQt6-Webengine.yml
```yaml
name: pyqt6-webengine
buildsystem: simple
build-commands:
  - sip-install
    --debug
    --verbose
    --concatenate=1
    --no-docstrings
    --qmake=/usr/bin/qmake6
    --target-dir=/app/lib/python3.9/site-packages/
    --api-dir=/app/lib/python3.9/site-packages/
build-options:
  - env:
      - QMAKEPATH=/app
sources:
  - type: archive
    url: https://pypi.python.org/packages/source/P/PyQt6-WebEngine/PyQt6_WebEngine-6.2.1.tar.gz
    sha256: 6f6d7cb612f20d1f1f8ea1bbe7ebb8bbaa3f7fcd56f0e9c41582851998be20c3
```

Output:
```
Running: sip-install --debug --verbose --concatenate=1 --no-docstrings --qmake=/usr/bin/qmake6 --target-dir=/app/lib/python3.9/site-packages/ --api-dir=/app/lib/python3.9/site-packages/
Querying qmake about your Qt installation...
/usr/bin/qmake6 -query
These bindings will be built: QtWebEngineCore, QtWebEngineQuick, QtWebEngineWidgets.
Generating the QtWebEngineCore bindings...
Generating the QtWebEngineCore .api file...
Generating the QtWebEngineQuick bindings...
Generating the QtWebEngineQuick .api file...
Generating the QtWebEngineWidgets bindings...
Generating the QtWebEngineWidgets .api file...
Generating the PyQt6-WebEngine.api file...
Generating the .pro file for the QtWebEngineCore module...
Generating the .pro file for the QtWebEngineQuick module...
Generating the .pro file for the QtWebEngineWidgets module...
Generating the top-level .pro file...
Generating the Makefiles...
/usr/bin/qmake6 -recursive PyQt6-WebEngine.pro
Info: creating stash file /tmp/tmp6sywpc_0/.qmake.stash
Reading /tmp/tmp6sywpc_0/QtWebEngineCore/QtWebEngineCore.pro
Project ERROR: Unknown module(s) in QT: webenginecore
sip-install: '/usr/bin/qmake6 -recursive PyQt6-WebEngine.pro' failed returning 3
Error: module pyqt6-webengine: Child process exited with code 1
```

Edit:
I had a typo. This is the working manifest, for everyone who is interested:
```yaml
name: pyqt6-webengine
buildsystem: simple
build-commands:
  - sip-install
    --debug
    --verbose
    --concatenate=1
    --no-docstrings
    --qmake=/usr/bin/qmake6
    --target-dir=/app/lib/python3.9/site-packages/
    --api-dir=/app/lib/python3.9/site-packages/
    --qmake-setting=QMAKE_INCDIR+=/app/include/QtWebEngineCore
    --qmake-setting=QMAKE_INCDIR+=/app/include/QtWebEngineQuick
    --qmake-setting=QMAKE_INCDIR+=/app/include/QtWebEngineWidgets
build-options:
    env:
      - QMAKEPATH=/app
sources:
  - type: archive
    url: https://pypi.python.org/packages/source/P/PyQt6-WebEngine/PyQt6_WebEngine-6.2.1.tar.gz
    sha256: 6f6d7cb612f20d1f1f8ea1bbe7ebb8bbaa3f7fcd56f0e9c41582851998be20c3
```

**Comment by FuchtelJockel** [comment]
@tinywrkb
Adding `-D_qt_additional_packages_prefix_paths` worked, if you want to build it yourself for testing you can look at https://github.com/flathub/net.jami.Jami/tree/beta-dev

**Comment by tinywrkb** [comment]
Possible runtime changes that can solve the CMake Qt modules package_find issue

### Solution 1

```
--- a/Qt6Config.cmake	2021-12-29 14:28:49.326714902 +0200
+++ b/Qt6Config.cmake	2021-12-29 14:28:07.787293407 +0200
@@ -189,6 +189,8 @@
         PATHS
             ${_qt_cmake_dir}
             ${_qt_additional_packages_prefix_paths}
+            "/app/lib/cmake"
+            "/app/lib/${CMAKE_CXX_LIBRARY_ARCHITECTURE}/cmake"
             ${QT_EXAMPLES_CMAKE_PREFIX_PATH}
             ${__qt_find_package_host_qt_path}
         ${__qt_use_no_default_path_for_qt_packages}
```

### Solution 2

This requires setting `QT_ADDITIONAL_PACKAGES_PREFIX_PATH=/app` as environment or CMake variable.  
I hope my regex match is correct.

```
--- a/Qt6Config.cmake	2021-12-29 14:45:59.805721020 +0200
+++ b/Qt6Config.cmake	2021-12-29 14:45:35.266061839 +0200
@@ -108,10 +108,12 @@
         # NO_DEFAULT_PATH, and thus CMAKE_PREFIX_PATH values are discarded.
         # CMAKE_FIND_ROOT_PATH values are not discarded and togegher with the PATHS option, it
         # ensures packages from additional prefixes are found.
-        if(NOT _qt_additional_path MATCHES "/lib/cmake$")
-            string(APPEND _qt_additional_path "/lib/cmake")
+        if(NOT _qt_additional_path MATCHES "/lib(/${CMAKE_CXX_LIBRARY_ARCHITECTURE})?/cmake$")
+            list(APPEND _qt_additional_packages_prefix_paths "${_qt_additional_path}/lib/cmake")
+            list(APPEND _qt_additional_packages_prefix_paths "${_qt_additional_path}/lib/${CMAKE_CXX_LIBRARY_ARCHITECTURE}/cmake")
+        else()
+            list(APPEND _qt_additional_packages_prefix_paths "${_qt_additional_path}")
         endif()
-        list(APPEND _qt_additional_packages_prefix_paths "${_qt_additional_path}")
     endforeach()
     unset(_qt_additional_path)
     unset(_qt_additional_packages_prefixes)
```

/ping @aleixpol

**Comment by tinywrkb** [comment]
If this still builds, and nothing is broken, then it pretty close to done. I just have a few small fixes that I'm holding back until the latest CI run will end.

With the latest changes, we should be able to avoid setting `QMAKE_INCDIR`. e.g. `QMAKE_INCDIR+=/app/include/QtWebEngineCore`.  

I haven't found a way to avoid setting `_qt_additional_packages_prefix_paths` without changing `Qt6Config.cmake` from the runtime.  

I'm not sure yet if we still need to set `QMAKEPATH=/app`, if it's still required, then maybe it can be set in the runtime's `qconfig.pri`. **edit:** We still need to set `QMAKEPATH`.

**Comment by tinywrkb** [comment]
Ready for review.

**Comment by tinywrkb** [comment]
I filed a [runtime bug report about the CMake config issue](https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/29)

**Comment by tinywrkb** [comment]
I pushed a minor change to the CMake Qt versions patching script.  
The base app builds fine locally with this change, and qutebrowser still builds correctly against the update base app.

I don't plan to make any more changes to this PR, and as far as I concern, this can be merged as it is into a new `branch/6.2` branch.

**Comment by tinywrkb** [comment]
Latest changes:
* Add pkgconfig file for snappy. Only needed for QtWebEngine `5.15.x`, but I prefer to keep the modules in the different maintained branches the same, if possible.
* Simpler Qt version dependency patching.

Both changes already tested in #32.

**Comment by tinywrkb** [comment]
Done! Just need to be pulled into a new `branch/6.2` branch.

**Comment by aleixpol** [comment]
Please retarget to branches/6.2

**Comment by tinywrkb** [comment]
I'm not sure if it's possible to target to a non-existing branch.

**Comment by JakobDev** [comment]
@tinywrkb As far as I know that is impossible. @aleixpol needs to make a 6.2 branch, so that you can retarget.

**Comment by tinywrkb** [comment]
Considering the fact that we set the `branch` property in the manifest, creating a `6.2.` by checking out 29b37fa99c3efed90ea9202131f0c79973cb4636 just for the sake of having the merge button here work, will not be a good idea, as the CI might build from this commit, and then update the ostree ref of the `5.15-21.08` Flatpak branch.  
So I suggest to just check out 29b37fa99c3efed90ea9202131f0c79973cb4636 locally as `branch/6.2`, fetch my [rt62 branch](https://github.com/tinywrkb/io.qt.qtwebengine.BaseApp/tree/rt62), and merge to the local `branch/6.2` branch and then push it as a new `branch/6.2` branch here.  

After this, I can change the base of the PR here, GitHub will warn that there no new commits were introduced, but it will allow for the maintainer to press on the merge button, or at least unless Flathub devs set a rule to disallow empty merge commit.

**Comment by aleixpol** [comment]
Happy to do so, could you please rebase your branch onto `branch/5.15-21.08`?

**Comment by tinywrkb** [comment]
Done!

**Comment by aleixpol** [comment]
Branch pushed!
https://github.com/flathub/io.qt.qtwebengine.BaseApp/tree/branch/6.2

**Comment by tinywrkb** [comment]
Thanks!

**Pull request closed without merging**
