### PR TITLE
Update to 5.15.7-lts, and apply changes from the 6.2 PR

### LINKED ISSUE #19: include QtWebView
Thank you for this extremely helpful package!

I would like to suggest including the QtWebView module in addition to QtWebEngine. As it stands now, the package does include QtWebEngine, which is arguably the more difficult of the two builds, but does not include the header files required to build the much simpler QtWebView and its plugin for QtWebEngine. 

I maintain an app that uses QtWebView and would be grateful for any ready-made package that I could use.

And again: thank you for providing the package!

### PR DESCRIPTION
**Pull request by tinywrkb**
## Highlights:
  - No need to set `QMAKE_INCDIR`
  - New shared libs: `krb5`, `libevent`, `minizip`, `pciutils`, `re2`, `snappy`
  - QtWebView was added

## Changes:
  - Update QtWebEngine to 5.15.7-lts 
  - Drop unneeded patches that included in 5.15.7-lts:
    - `chromium-skia-harfbuzz-3.0.0.patch`
    - `chromium-skia-harfbuzz-3.0.0.patch`
    - `qt5-webengine-glibc-2.33.patch`
  - Use `FLATPAK_DEST` as much as possible
  - pciutils: drop `PREFIX` install argument
  - Simpler workaround for the Qt patch version dependency
  - Add `krb5` and enable Kerberos in QtWebEngine
  - Use `FLATPAK_ARCH` instead of executing `gcc --print-multiarch`
  - Move modules into separate manifests that can be tested without having to build the base app
  - Avoid Chromium in-tree libs by adding them as modules: `libevent`, `minizip`, `re2`, `snappy,
  - Keep `pciutils` as a shared lib in the base app
  - Disable locale extensions creation now that we have `/app/share/locale`
  - No need to set `QMAKE_INCDIR` anymore (e.g `QMAKE_INCDIR+=/app/include/QtWebEngineCore`), as include dirs
    path in modules' project include files (pri) are now correct
  - Correct `prefix` in pkgconfig files of Qt5 modules
  - Keep PipeWire's headers. Needed for building Chromium with the published base app
  - Build with Python 3
  - Add QtWebView
  - Install with the correct prefix instead of using scratchdir

Supersedes: #21, #24, #26, #27, #28.  
Closes #19.

### CODE REVIEW

**Comment by tinywrkb** [comment]
Looks good so far, qutebrowser still working with this.

**Comment by tinywrkb** [comment]
Hopefully should be now ready for testing.  
After the current CI run, I will push a minor git message changes, and if everything checks out, then this will supersede #28.

**Comment by tinywrkb** [comment]
Looks fine over here. qutebrowser builds and runs correctly with the latest build.  
Ready for merging.

**Comment by aleixpol** [comment]
Looks good, thanks a lot!

**Comment by tinywrkb** [comment]
Thanks for merging!

**Pull request merged**
