### PR TITLE
DO NOT MERGE - 22.08 runtime:

### PR DESCRIPTION
**Pull request by hfiguiere**
- added python 3.10 fixes (FTBS)
- ~~added ffmpeg5 fixes, still broken~~ we no longer use "system" ffmpeg
- added gcc 12 patch

### CODE REVIEW

**Comment by hfiguiere** [comment]
Cancelled the first build. This add the latest flathub PR that was never merged.

**Comment by hfiguiere** [comment]
```
FAILED: obj/media/filters/filters/filters_jumbo_5.o 
/usr/bin/g++ -MMD -MF obj/media/filters/filters/filters_jumbo_5.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -DTOOLKIT_QT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DIS_MEDIA_IMPL -DUSE_PULSEAUDIO -DDLOPEN_PULSEAUDIO -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_USE_LIBGIFCODEC -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DUCHAR_TYPE=uint16_t -DCONFIG_LOG=0 -DSTACK_ALIGNMENT=32 -DDAV1D_API= -I. -Igen -I../../../../src/3rdparty/chromium -I../../../../src/3rdparty/chromium/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen -Igen -Igen -Igen -Igen -Igen -Igen -I../../../../src/3rdparty/chromium/third_party/vulkan_headers/include -Igen -I../../../../src/3rdparty/chromium/third_party/libyuv/include -Igen -Igen -Igen -Igen -I../../../../src/3rdparty/chromium/third_party/khronos -I../../../../src/3rdparty/chromium/gpu -Igen -I../../../../src/3rdparty/chromium/third_party/abseil-cpp -I../../../../src/3rdparty/chromium/third_party/boringssl/src/include -I../../../../src/3rdparty/chromium/third_party/protobuf/src -Igen/protoc_out -I../../../../src/3rdparty/chromium/third_party/skia -I../../../../src/3rdparty/chromium/third_party/libgifcodec -I../../../../src/3rdparty/chromium/third_party/vulkan/include -I../../../../src/3rdparty/chromium/third_party/vulkan_headers/include -I../../../../src/3rdparty/chromium/third_party/mesa_headers -I../../../../src/3rdparty/chromium/third_party/dav1d/version -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -m64 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-packed-not-aligned -Wno-dangling-else -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -fvisibility=hidden -I/usr/include/opus -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -Wno-attributes -Wno-class-memaccess -Wno-subobject-linkage -Wno-invalid-offsetof -Wno-return-type -Wno-deprecated-copy -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c gen/media/filters/filters_jumbo_5.cc -o obj/media/filters/filters/filters_jumbo_5.o
In file included from gen/media/filters/filters_jumbo_5.cc:12:
./../../../../src/3rdparty/chromium/media/filters/ffmpeg_demuxer.cc: In function ‘base::TimeDelta media::ExtractStartTime(AVStream*)’:
./../../../../src/3rdparty/chromium/media/filters/ffmpeg_demuxer.cc:101:7: error: ‘av_stream_get_first_dts’ was not declared in this scope; did you mean ‘av_stream_get_side_data’?
  101 |   if (av_stream_get_first_dts(stream) != kNoFFmpegTimestamp &&
      |       ^~~~~~~~~~~~~~~~~~~~~~~
      |       av_stream_get_side_data
[11093/23907] /usr/bin/g++ -MMD -MF obj/media/m
```

the ffmpeg patch is insufficient.

**Comment by tinywrkb** [comment]
I haven't really looked at this, but see [upstream bug report](https://bugreports.qt.io/browse/QTBUG-105815), and also [here](https://github.com/archlinux/svntogit-packages/blob/packages/ffmpeg/trunk/add-av_stream_get_first_dts-for-chromium.patch).  
Might have to add to the runtime.

**Comment by hfiguiere** [comment]
can't really with --system-ffmpeg.

**Comment by hfiguiere** [comment]
Building without `system-ffmpeg` seems to be the way to move forward (it didn't fail on ffmpeg) but I'm hitting other errors in Skia, probably related to new g++. Will investigate.

(it will take a bit as I still don't have a faster build machine)

**Comment by hfiguiere** [comment]
Seems we need that patch https://github.com/archlinux/svntogit-packages/blob/packages/qt5-webengine/trunk/qt5-webengine-gcc12.patch

**Comment by tinywrkb** [comment]
Works fine with qutebrowser.  
So far, no regressions in h264 playback, and from what I can tell the internal h264 decoder is not disabled when FFmpeg is built, unlike the runtime's libavcodec, which forces us to add the ffmpeg-full extension.  

I intend to skip this and switch directly to KDE 6.4 when the next major release of qutebrowser will be out, possibly building QtWebEngine from source to get out builds with security fixes faster, so we might want to reconsider fetching the latest commit of qtwebengine-chromium here, and just get it as a git submodule of the stable tagged QtWebEgnine release. That's if there's no other QtWebEngine based webbrowser.

**Comment by hfiguiere** [comment]
Branch has been created.

**Pull request closed without merging**
